version: '2'
services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: senzing-zookeeper
    ports:
      - '2181:2181'
    environment:
#     See https://github.com/bitnami/bitnami-docker-zookeeper#configuration
      ALLOW_ANONYMOUS_LOGIN: "yes"
    restart: always
    networks:
      - backend

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: senzing-kafka
    ports:
      - '9092:9092'
    environment:
#     See https://github.com/bitnami/bitnami-docker-kafka#configuration
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_NUM_PARTITIONS: 6
    depends_on:
      - zookeeper
    restart: always
    networks:
      - backend

  mockdata:
    image: senzing/mock-data-generator
    container_name: senzing-mock-data-generator
    environment:
#     See https://github.com/Senzing/docker-mock-data-generator#configuration
      SENZING_SUBCOMMAND: url-to-kafka
      SENZING_KAFKA_BOOTSTRAP_SERVER: senzing-kafka:9092
      SENZING_KAFKA_TOPIC: "senzing-kafka-topic"
      SENZING_INPUT_URL: "https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
      SENZING_RECORD_MAX: 10000
      SENZING_RECORD_MONITOR: 100
      SENZING_RECORDS_PER_SECOND: 10
    networks:
      - backend
    depends_on:
      - kafka
    restart: on-failure

  mysql:
    image: mysql:5.7
    container_name: senzing-mysql
    environment:
#     See https://hub.docker.com/_/mysql/ "Environment Variables"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: G2
      MYSQL_USER: g2
      MYSQL_PASSWORD: g2
    restart: always
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - /storage/docker/senzing/docker-compose-mysql-demo:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: senzing-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - backend
    ports:
      - 8080:80
    restart: always
    depends_on:
      - mysql

  loader:
    image: senzing/stream-loader
    container_name: senzing-stream-loader-1
    environment:
      LC_CTYPE: en_US.utf8
#     See https://github.com/Senzing/stream-loader#configuration
      SENZING_DATA_SOURCE: ${SENZING_DATA_SOURCE:-TEST}
      SENZING_ENTITY_TYPE: ${SENZING_ENTITY_TYPE:-TEST}
      SENZING_KAFKA_BOOTSTRAP_SERVER: senzing-kafka:9092
      SENZING_KAFKA_TOPIC: "senzing-kafka-topic"
      SENZING_SUBCOMMAND: kafka
    networks:
      - backend
    volumes:
      - /opt/senzing:/opt/senzing
    restart: on-failure

networks:
  backend:
